### PR TITLE
some cleanups and fix a crasher

### PR DESCRIPTION
**Pull request by palacaze**
I simplified the .pro file somewhat in order to use INCLUDEPATH and LIBS added by qtcreator.pri as intended.

This is not necessarily a request for merge, but a proposal. I can rebase it off your testing branch if you want.

### CODE REVIEW

**Comment by fpoussin** [comment]
Hey,

Plugins classes are singleton, I'm not sure this is a good idea to remove the static instance() method.
As far as I know it's only used to interact between plugins.

Example:
```
CppTools::CppModelManager *modelManager = CppTools::CppModelManager::instance();
```

You will have to rebase and probably fix some conflicts, I will rebase the master on the testing branch when I'm done.

Thanks!

**Comment by palacaze** [comment]
Hi,

Ok I did not realize the inter-plugin interaction purpose, as I based my understanding of the plugin system from the beautifier plugin, which sort of a end-user plugin (not meant to be used by another plugin). Many more plugins don't exhibit this behaviour

Anyway, I will restore the singleton functionality of the DoxygenPlugin as we can't ascertain it won't ever be used from another plugin.

**Comment by palacaze** [comment]
Ok I rebased this.

I tried to leave the .pro file as unspecific as possible without changing your settings. But As a matter of fact it may have a small impact with the introduction of IDE_LIBRARY_BASENAME, which defaults to "lib" in qtcreator.pri, and is set to "usr/lib64" on my Gentoo system. Yours seems to be "usr/lib/x86_64-linux-gnu", whereas IDE_BUILD_TREE would be just "/" for both of us on the installed version, and obviously varies for a locally built directory.

Feel free to change that.

**Comment by palacaze** [comment]
Sigh... embarrassing crasher. Core::IOptionsPage::apply() is called unconditionally.

**Comment by fpoussin** [comment]
Thanks a lot!

**Pull request merged**
